app_name: "Posebuddy"
image_dir: "train_job/images"
presence_image_dir: "presence_train_job/images"
job_dir: "train_job"
presence_job_dir: "presence_train_job"
json_file_name: "data.json"
presence_json_file_name: "presence_data.json"
update_period_ms: 100
present_timer_sec: 3600
cam_num: 0
always_on_top: True
